### PR TITLE
Added method addTagsMember() to MailchimpLists.

### PR DESCRIPTION
**Pull request by MegaChriz**
It would be useful to have a method to add tags to a member.

See https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/tags/

### CODE REVIEW

**Comment by collizo4sky** [comment]
@ruscoe We need this please.

**Comment by MegaChriz** [comment]
I've also added a method now to remove tags.

And I made two corrections in MailchimpList::addTagsMember():
- use strtolower() for creating the hash for email.
- add link to documention in the docblock.

**Comment by ruscoe** [comment]
@collizo4sky I don't have commit access to this repo anymore. Sorry!

**Comment by MegaChriz** [comment]
@ruscoe So who maintains this repo now?

**Comment by collizo4sky** [comment]
Who does?

**Comment by ruscoe** [comment]
Somebody at [ThinkShout](https://github.com/thinkshout) will need to comment on that. I don't know how they're doing things now.

**Comment by mortenson** [comment]
Sorry for the delay - I'm just now going through the queue after quite some time. Thanks for the contribution!

**Pull request merged**
