### PR TITLE
PHP 8 fix: $parameter parameter of request() accepts an array as default not NULL

### PR DESCRIPTION
**Pull request by w3guy**
mailchimp-api-php/src/http/MailchimpCurlHttpClient.php calls http_build_query passing NULL which is an error in PHP 8.

### CODE REVIEW

**Comment by w3guy** [comment]
Can we get this merged asap? Cc @ruscoe @mariacha

**Comment by ruscoe** [comment]
@w3guy I don't have write access anymore, but I agree this one should be merged.

**Comment by w3guy** [comment]
@ruscoe know anyone who does that I can tag?

**Comment by ruscoe** [comment]
@mortenson is probably your best bet.

**Comment by w3guy** [comment]
@mortenson can you please merge and tag this?

**Comment by mortenson** [comment]
I don't work at ThinkShout anymore, so I will also pass it to @unclegcb

**Comment by w3guy** [comment]
@unclegcb can you please take a look?

**Comment by mariacha** [comment]
It seems straightforward but I wanted to do due diligence and test in php 7x. Looks good, and shows off a couple other places where the documentation doesn't match the parameter (tokens) that I'll make a followup ticket for.

**Comment by w3guy** [comment]
@mariacha thank you. Please don't forget to make a release or create a tag.

**Comment by mariacha** [comment]
Done! https://github.com/thinkshout/mailchimp-api-php/releases/tag/v2.1.1

**Pull request merged**
