### PR TITLE
Provide version as a constant for dependency checks

### PR DESCRIPTION
**Pull request by taz77**
This provides the version number as a constant out of the class. This is useful for testing from other code to make sure the correct version of the API is being loaded. I am working on some patches to submit on D.O that allows the Drupal module that you guys maintain to be used with or without the libraries module, such as using composer (which I do on D7). Adding the version into the class will allow for checking of the version number from the hook_requirements as an optional method to libraries.

Updated the composer.json to not load the test classes if you are running --no-dev (good for production sites).

### CODE REVIEW

**Comment by taz77** [comment]
Note that I did not roll the version number. If you release a new version the constant and the string in the test needs to be changed.

**Comment by taz77** [comment]
I included a Travis YAML if you want to run CI testing for the library.

**Comment by taz77** [comment]
Any feedback on if this is can be included in the module?

**Comment by ruscoe** [comment]
Sorry for the delay in getting to this. Is there any reason to keep the commented lines in `.travis.yml`?

**Comment by taz77** [comment]
No there is not reason for them to be there. I just removed them.

**Comment by taz77** [comment]
Cool thanks! I am working on adding the eCommerce stuff to your API. Look for that pull request in the future.

**Comment by ruscoe** [comment]
Awesome, thank you. You might have already seen this, but we made a start on eCommerce in this branch:

https://github.com/thinkshout/mailchimp-api-php/commits/ecommerce

**Comment by taz77** [comment]
Crap. I missed that. Is there anyway I can help. I need that to finish my transition to Mailchimp.  You guys have any plans in the near future to do more work or will it be ok if I fork that branch? I am not the fastest when it comes to churning stuff out because I do this in my spare time (i.e. this isn't my day job).

**Comment by ruscoe** [comment]
We're likely to start work on it again in the next few weeks. You can definitely fork it. I would recommend making small pull requests as you finish features and I'll make a point to be more proactive about merging them in. That way I think we can avoid duplicating any work.

We also started a new module for eCommerce:

https://github.com/thinkshout/mailchimp_ecommerce

There's only a Drupal 7 version right now, but we'll be creating one for Drupal 8 as well.

**Pull request merged**
