### PR TITLE
Issue 3189464 integrate events

### PR DESCRIPTION
**Pull request by mariacha**
Adds the AddMemberEvent and getMemberEvents methods, plus unit tests.

Based on 
https://mailchimp.com/developer/marketing/api/list-member-events/add-event/

and
https://mailchimp.com/developer/marketing/api/list-member-events/list-member-events/

I think this is actually ready for review/merge, based on the prototype & testing instructions in this PR: https://github.com/thinkshout/inkling/pull/5

### CODE REVIEW

**Comment by mariacha** [comment]
Hi @spncr! -- Gabe mentioned you've been doing a lot of Mailchimp module maintenance lately. Want to review this PR? It's related to https://github.com/thinkshout/support/issues/37 and functionally testable on this inkling branch: https://github.com/thinkshout/inkling/pull/5

**Review by unclegcb — APPROVED** [review]
Looks good to me: appreciate the test coverage too!

**Review by spncr — APPROVED** [review]
Hey thanks for including me on this! 

It makes sense to read, but would probably take me a while to write myself.

**Comment by mariacha** [comment]
Thanks all!

**Pull request merged**
